name: Validate & Upload Servers
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  validate-servers:
    runs-on: ubuntu-latest
    name: Validating Servers
    steps:
      - uses: actions/checkout@v1
        name: Checkout from GitHub

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: servers.schema.json
          INPUT_JSONS: servers.json

  upload-servers:
    runs-on: ubuntu-latest
    name: Uploading Servers
    needs: validate-servers
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-2

      - name: Setup Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: pip install webptools Pillow

      - name: Prepare Server Logos
        run: python prepare_logos.py --input servers.json --source logos --destination _out/logos

      - name: Move servers.json to upload directory
        run: |
          cp servers.json _out/
          
      - name: Upload to S3
        run: aws s3 sync _out s3://lcservermappings --delete --cache-control "public, max-age=604800, immutable"

      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/95640333e362c043bb8f4be28ac53524/purge_cache" -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}" -H "Content-Type: application/json" --data '{"hosts":["servermappings.lunarclientcdn.com"]}'
